name: life_log
description: A simple log app.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  core:
    path: ../../packages/core
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  frontend:
    path: ../../packages/frontend
  get_it: ^7.6.4
  path: ^1.8.2
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  utils:
    path: ../../packages/utils
  video_player: ^2.7.2

flutter_icons:
  android: true
  ios: true
  image_path: "icons/icon.png"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "icons/icon.png"

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - icons/icon.png
    - icons/LifeLog.MP4
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
